# Done to increase the memory available to gradle.
org.gradle.jvmargs=-Xmx1G

# Fabric Properties
# check these on https://modmuss50.me/fabric.html
minecraft_version=26.3
loader_version=0.19.5
loom_version=1.16-SNAPSHOT

# Mod Properties
mod_version = 1.0
maven_group = io.github.jerozgen
archives_base_name = item-hunt

# Dependencies
fabric_api_version=0.160.5+26.3
plasmid_version=0.7.3-SNAPSHOT+26.3
